name: 'AI PR Code Reviewer'
description: 'OPENAI based pull request(merge request) code reviewer'
author: 'Zelalem Tenaw Terefe'

inputs:
  repository-name:
    description: |
      The name of the repository for your project. It can be manually retrieved by going to the 
      github project or using github event metadata like this: ${{ github.event.repository.name }}.
      The second option is recommended.
    required: true
  repository-owner:
    description: ''
    required: true
  pull-request-number:
    description: ''
    required: true
  github-api-token:
    description: ''
    required: true
  coding-language:
    description: ''
    required: true
  open-ai-token:
    description: ''
    required: true
  gpt-model:
    description: ''
    required: false
  temperature:
    description: ''
    required: false
  prompt-message:
    description: ''
    required: true

outputs:
  pull-request-number:
    description: 'The number for the pull request that was reviewed'

runs:
  using: 'node20'
  main: 'dist/index.js'